### ISSUE TITLE
Add ModelNode.ToSourceCode() extension 

### ISSUE THREAD

**Issue by SubPointSupport** [SubPointSolutions/spmeta2-reverse#74]
Reverse library should support .ToSourceCode() extension so that a pure C# code can be generated out of the ModelNode instance.

Roslyn / ILSpy can be suggested as a code generation engine if needed.
Should be a separate project such as  SPMeta2.Reverse.CodeDom or  SPMeta2.CodeDom project.

**Comment by rolandoldengarm** [comment]
First impression was YES, but then I thought: what would this generate? What type of code? What can I do with it?

**Comment by SubPointSupport** [comment]
The original source code will be generated as per our M2 Intranet model VS project, following the same guidelines and conventions. Optimally, some parameters can be provided too.

https://github.com/SubPointSolutions/spmeta2-vsixextensions/wiki/M2-Intranet-Model-project

With Roslyn we can hit incremental updated C# code generation. That means that second and further source code generation can have several options:
* Updates will NOT override manual changes done by developer
* Updates will override the whole mode (or part)
* Update will only ADD on top the props / artifacts which aren't there

Sounds pretty hardcore yet realistic.

**Comment by rolandoldengarm** [comment]
Yes, pretty hardcode :) I still don't see the benefit. If you have the ModelNode, in most cases you'd have the original source code? What is the usecase of this?

**Comment by SubPointSupport** [comment]
@rolandoldengarm , that's spmeta2-reverse repo :) 

The thing is pure opposite to M2: the M2 Reverse library generates the ModelNode based on the existing SharePoint web. We don't have the source code. We go after existing SharePoint web site, fetch the artifacts and make the correct definitions / model nodes.

**Comment by SubPointSupport** [comment]
Well, let's say Entity Framework has the code-first approach - that's what M2 does well. But Entity Framework also has a code-generation way of getting already existing DB into C# POCOs. That's what M2 Reverse can be all about.

Hope that gives more visibility on what are the potentials we are exploring with the reverse library.

**Comment by rolandoldengarm** [comment]
Ah, that would be awesome!! We've reverse engineered manually (well, I created a script to create the C# code), but a library would be REALLY helpful.

+1 for me.

**Comment by SubPointSupport** [comment]
What was the case to have a script for code-generation? How often do you have it?

**Comment by rolandoldengarm** [comment]
We built a site for a client by clicking (i.e. creating everything manually), because it was a one-time site. Then client decides he wants to reuse it, so I created a console app to generate C# code for SPMeta2.

**Comment by SubPointSupport** [comment]
Separated into spmeta2-schema project. We need a dedicated layer for a wider model conversion - not only to support CSharp but also to support other formats such as XML, JSON, YAML. 

For the further updates, track the following issue:
- Implement CSharp provider #10
https://github.com/SubPointSolutions/spmeta2-schema/issues/10
